//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class announcement
    {
        public int announcement_id { get; set; }
        public string announcement_title { get; set; }
        public string announcement_details { get; set; }
        public Nullable<System.DateTime> announcement_date { get; set; }
    }
}
