//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int chat_id { get; set; }
        public Nullable<int> chat_from { get; set; }
        public Nullable<int> chat_to { get; set; }
        public string chat_message { get; set; }
        public Nullable<System.DateTime> datetime_sent { get; set; }
        public Nullable<System.DateTime> datetime_read { get; set; }
    }
}
