//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eq_prod
    {
        public int eq_prod_id { get; set; }
        public string queue_name { get; set; }
        public string Process_Instance_ID { get; set; }
        public string Work_Item_ID { get; set; }
        public string Intake_CPU { get; set; }
        public string BU_ID { get; set; }
        public string Cust_ID { get; set; }
        public string Requeued_Queue_Name { get; set; }
        public Nullable<System.DateTime> Task_Create_Date_Time { get; set; }
        public string Process_Type { get; set; }
        public string Task_Status { get; set; }
        public string Task_Resolution { get; set; }
        public Nullable<decimal> Idle_Seconds { get; set; }
        public Nullable<decimal> Handling_Seconds { get; set; }
        public Nullable<decimal> Duration_Seconds { get; set; }
        public Nullable<int> Touch_Count { get; set; }
        public string Last_Associate_ID { get; set; }
        public string Last_Associate_Name { get; set; }
        public string Last_Associcate_Manager { get; set; }
        public string Last_Associate_Site { get; set; }
        public Nullable<System.DateTime> First_Assignment_Timestamp { get; set; }
        public Nullable<System.DateTime> Last_Assignment_Timestamp { get; set; }
        public Nullable<System.DateTime> Last_Assignment_Date { get; set; }
        public Nullable<System.DateTime> Task_Create_Date { get; set; }
        public Nullable<System.DateTime> Task_Resolved_Timestamp { get; set; }
        public string Last_Follow_Up_Code { get; set; }
        public Nullable<System.DateTime> Last_Follow_Up_Code_Timestamp { get; set; }
        public string NEB { get; set; }
        public string PAP { get; set; }
        public string O2_RNTL { get; set; }
        public string NI_VENT { get; set; }
        public string NPWT { get; set; }
        public string PAP_SUPPLY { get; set; }
        public string OTHER { get; set; }
        public string BED { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> SAP_ID { get; set; }
        public string CITRIX_ID { get; set; }
        public string Name { get; set; }
        public string Supervisor { get; set; }
        public string Wave { get; set; }
        public string Track_Roster_Wise { get; set; }
        public string Track_Queue_Wise { get; set; }
        public string Division { get; set; }
    }
}
