//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HCL_HRISEntities : DbContext
    {
        public HCL_HRISEntities()
            : base("name=HCL_HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<audit> audits { get; set; }
        public virtual DbSet<eq_prod> eq_prod { get; set; }
    
        public virtual ObjectResult<get_Errors_Result> get_Errors(Nullable<int> sap_id)
        {
            var sap_idParameter = sap_id.HasValue ?
                new ObjectParameter("sap_id", sap_id) :
                new ObjectParameter("sap_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Errors_Result>("get_Errors", sap_idParameter);
        }
    
        public virtual ObjectResult<get_QualityRanks_Result> get_QualityRanks(Nullable<int> sapid)
        {
            var sapidParameter = sapid.HasValue ?
                new ObjectParameter("sapid", sapid) :
                new ObjectParameter("sapid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_QualityRanks_Result>("get_QualityRanks", sapidParameter);
        }
    
        public virtual ObjectResult<get_Prod_Result> get_Prod(Nullable<int> sap_id)
        {
            var sap_idParameter = sap_id.HasValue ?
                new ObjectParameter("sap_id", sap_id) :
                new ObjectParameter("sap_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Prod_Result>("get_Prod", sap_idParameter);
        }
    }
}
