//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HCL_HRISEntities : DbContext
    {
        public HCL_HRISEntities()
            : base("name=HCL_HRISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<track> tracks { get; set; }
    }
}
