//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL_HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        public int track_id { get; set; }
        public string track_name { get; set; }
        public Nullable<int> track_manager { get; set; }
    }
}
